### ISSUE TITLE
Environments of the project

### ISSUE THREAD

**Issue by KinokoG** [BoaSahiro/11785TimbreTransfer#1]
Hi Yuxuan, I am very inspired by your paper and would like to thank you for sharing your code, I would like to ask if you can provide the environment requirements for the project or a readme file that would help me to reproduce your paper. Thanks!

**Comment by Irislucent** [comment]
Hi, thank you for your interest! Now the repo has been updated. Hope that helps!

**Comment by Irislucent** [comment]
Hi, thank you for your interest! Now the repo has been updated. Hope that helps!
